### ISSUE TITLE
Validação

### ISSUE THREAD

**Issue by jcanongia** [joaojuniormail/validaform#1]
Bom Dia!
Uso Laravel 5.2. Estou fazendo os imput via form

<div class="form-group">
      {!! Form::label('cpf', 'Cpf:', ['class' => 'col-sm-2 control-label']) !!}
      <div class="col-sm-9">
         {!! Form::text('cpf', null, ['class' => 'form-control cpf', 'data-msgvalidate'=>'CPF errado']) !!}
      </div>

Consegui aplicar a mascara no CPF, mas não realiza a validação.
Pode me ajudar?

**Comment by joaobsjunior** [comment]
Você deve criar um elemento para erro e sucesso.

Em terça-feira, 5 de abril de 2016, Jose Canongia notifications@github.com
escreveu:

> Bom Dia!
> Uso Laravel 5.2. Estou fazendo os imput via form
> {!! Form::label('cpf', 'Cpf:', ['class' => 'col-sm-2 control-label']) !!}
> {!! Form::text('cpf', null, ['class' => 'form-control cpf',
> 'data-msgvalidate'=>'CPF errado']) !!}
> 
> Consegui aplicar a mascara no CPF, mas não realiza a validação.
> Pode me ajudar?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/joaojuniormail/validaform/issues/1

## 

Att.

João Batista da Silva Júnior

## Systems Analyst - Capgemini | Mobile Applications

**Comment by jcanongia** [comment]
Obrigado pela resposta pronta.

Na verdade observei que meu erro era que para ser verificado a validade o
campo precisava ser "required", falei besteira?
Acertei este "if" e funcionou.

Obrigado mais uma vez.
Abç

José Canongia
Gerente de Sistemas

2016-04-05 19:12 GMT-03:00 joaojuniormail notifications@github.com:

**Comment by joaobsjunior** [comment]
Ahh ta. Pensei que vc já tinha adicionado o atributo, mas para mostrar a
validacao é necessário criar as divs de sucesso e falha

Em quarta-feira, 6 de abril de 2016, Jose Canongia notifications@github.com
escreveu:

> Obrigado pela resposta pronta.
> 
> Na verdade observei que meu erro era que para ser verificado a validade o
> campo precisava ser "required", falei besteira?
> Acertei este "if" e funcionou.
> 
> Obrigado mais uma vez.
> Abç
> 
> José Canongia
> Gerente de Sistemas
> 
> 2016-04-05 19:12 GMT-03:00 joaojuniormail <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>:
> 
> > Você deve criar um elemento para erro e sucesso.
> > 
> > Em terça-feira, 5 de abril de 2016, Jose Canongia <
> > notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > escreveu:
> > 
> > > Bom Dia!
> > > Uso Laravel 5.2. Estou fazendo os imput via form
> > > {!! Form::label('cpf', 'Cpf:', ['class' => 'col-sm-2 control-label'])
> > > !!}
> > > {!! Form::text('cpf', null, ['class' => 'form-control cpf',
> > > 'data-msgvalidate'=>'CPF errado']) !!}
> > > 
> > > Consegui aplicar a mascara no CPF, mas não realiza a validação.
> > > Pode me ajudar?
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/joaojuniormail/validaform/issues/1
> > 
> > ## 
> > 
> > Att.
> > 
> > João Batista da Silva Júnior
> > 
> > ## Systems Analyst - Capgemini | Mobile Applications
> > 
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/joaojuniormail/validaform/issues/1#issuecomment-206004076
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/joaojuniormail/validaform/issues/1#issuecomment-206409077

## 

Att.

João Batista da Silva Júnior

## Systems Analyst - Capgemini | Mobile Applications
